import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, existsSync } from "fs";

// Load .env if present (gitignored — set NOS_VAULT_PLUGIN_DIR here)
if (existsSync(".env")) {
  for (const line of readFileSync(".env", "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    if (key && !process.env[key]) process.env[key] = val;
  }
}

// @huggingface/transformers ships a webpack UMD bundle whose runtime throws
// "Automatic publicPath is not supported in this browser" when loaded in
// Obsidian's plugin context (no real <script> tag → no currentScript.src).
// Patch the throw to a CDN fallback so webpack sets __webpack_public_path__
// to the correct base URL. The actual WASM paths are further overridden via
// env.backends.onnx.wasm.wasmPaths in database.ts before pipeline() is called.
const patchTransformers = {
  name: "patch-transformers-public-path",
  setup(build) {
    build.onLoad({ filter: /transformers\.min\.js$/ }, (args) => {
      let contents = readFileSync(args.path, "utf-8");
      // The minified bundle uses comma-operator form: if(...,!e)throw new Error(...)
      // where 'e' is the minified local variable name. Inject a CDN fallback assignment
      // before the falsy check so 'e' is always set and the throw is never reached.
      const CDN = "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/dist/transformers.min.js";
      const needle = /(,!([\w$]+)\))throw new Error\("Automatic publicPath is not supported in this browser"\)/;
      const match = contents.match(needle);
      if (match) {
        const v = match[2]; // minified var name, e.g. "e"
        // Insert: ,(v||(v="CDN")),!v) before the throw — makes the condition false
        contents = contents.replace(needle,
          `,(${v}||(${v}="${CDN}")),!${v})throw new Error("Automatic publicPath is not supported in this browser")`
        );
        console.log(`[patch-transformers] publicPath throw bypassed (var=${v})`);
      } else {
        console.error("[patch-transformers] publicPath needle not found — @huggingface/transformers bundle changed.");
        console.error("Update the regex in esbuild.config.mjs to match the new bundle format.");
        process.exit(1);
      }

      // In Electron's renderer process, process.release.name === "node", so
      // IS_NODE_ENV is true and transformers picks onnxruntime-node (native bindings)
      // instead of onnxruntime-web (WASM).  Native bindings don't exist in an
      // Obsidian plugin → InferenceSession.create() is undefined and crashes.
      // Force the web/WASM path by skipping the IS_NODE_ENV branch entirely.
      const nodeEnvNeedle = "else if(s.apis.IS_NODE_ENV){";
      if (contents.includes(nodeEnvNeedle)) {
        contents = contents.replace(nodeEnvNeedle, "else if(false){");
        console.log("[patch-transformers] IS_NODE_ENV branch disabled → WASM backend forced");
      } else {
        console.error("[patch-transformers] IS_NODE_ENV needle not found — bundle may have changed.");
        process.exit(1);
      }

      // The `Se` loader does `import(cdnUrl)` to fetch the Emscripten .mjs glue
      // from CDN.  That .mjs statically imports `worker_threads`, which fails in
      // Obsidian's renderer (browser ESM context can't resolve Node.js built-ins).
      // The identical Emscripten module is already bundled as `Ie` (the rd() lazy
      // init).  Redirect Se to return the bundled module instead of fetching CDN.
      const seNeedle = "Se=async e=>(await import(e)).default";
      if (contents.includes(seNeedle)) {
        contents = contents.replace(seNeedle, "Se=async e=>Ie");
        console.log("[patch-transformers] Se CDN importer → bundled Ie (worker_threads fix)");
      } else {
        console.error("[patch-transformers] Se CDN importer needle not found — transformers bundle changed.");
        process.exit(1);
      }

      return { contents, loader: "js" };
    });
  },
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  plugins: [patchTransformers],
  alias: {
    "@huggingface/transformers": "./node_modules/@huggingface/transformers/dist/transformers.min.js"
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  platform: "node",
});

if (prod) {
  await context.rebuild();

  // Copy the WASM binary from transformers' dist into the plugin directory so
  // database.ts can load it via fs.readFileSync(__dirname + '/...') at runtime,
  // bypassing all URL-fetch issues in Electron's renderer.
  const WASM_SRC = "./node_modules/@huggingface/transformers/dist/ort-wasm-simd-threaded.jsep.wasm";
  const WASM_NAME = "ort-wasm-simd-threaded.jsep.wasm";
  const { copyFileSync: _copy } = await import("fs");
  try {
    _copy(WASM_SRC, WASM_NAME);
    console.log(`[deploy] WASM → ${WASM_NAME}`);
  } catch (e) {
    console.warn(`[deploy] WASM copy failed: ${e.message}`);
  }

  // Optional: auto-deploy to local vault. Set NOS_VAULT_PLUGIN_DIR env var to enable.
  // Example: NOS_VAULT_PLUGIN_DIR="/path/to/vault/.obsidian/plugins/narrative-os" npm run build
  const deployDir = process.env.NOS_VAULT_PLUGIN_DIR;
  if (deployDir) {
    const { copyFileSync } = await import("fs");
    try {
      copyFileSync("main.js", `${deployDir}/main.js`);
      copyFileSync("manifest.json", `${deployDir}/manifest.json`);
      copyFileSync("styles.css", `${deployDir}/styles.css`);
      copyFileSync(WASM_NAME, `${deployDir}/${WASM_NAME}`);
      console.log(`[deploy] → ${deployDir}`);
    } catch (e) {
      console.warn(`[deploy] Failed: ${e.message}`);
    }
  }
  process.exit(0);
} else {
  await context.watch();
}
