import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync, existsSync } from "fs";

// Load .env if present (gitignored — set NOS_VAULT_PLUGIN_DIR here)
if (existsSync(".env")) {
  for (const line of readFileSync(".env", "utf-8").split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    if (key && !process.env[key]) process.env[key] = val;
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  alias: {
    "@huggingface/transformers": "./node_modules/@huggingface/transformers/dist/transformers.min.js"
  },
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  platform: "node",
});

if (prod) {
  await context.rebuild();
  // Optional: auto-deploy to local vault. Set NOS_VAULT_PLUGIN_DIR env var to enable.
  // Example: NOS_VAULT_PLUGIN_DIR="/path/to/vault/.obsidian/plugins/narrative-os" npm run build
  const deployDir = process.env.NOS_VAULT_PLUGIN_DIR;
  if (deployDir) {
    const { copyFileSync } = await import("fs");
    try {
      copyFileSync("main.js", `${deployDir}/main.js`);
      copyFileSync("manifest.json", `${deployDir}/manifest.json`);
      copyFileSync("styles.css", `${deployDir}/styles.css`);
      console.log(`[deploy] → ${deployDir}`);
    } catch (e) {
      console.warn(`[deploy] Failed: ${e.message}`);
    }
  }
  process.exit(0);
} else {
  await context.watch();
}
