/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => NarrativePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// src/api.ts
var NarrativeAPI = class {
  constructor(baseUrl) {
    this.baseUrl = baseUrl;
  }
  updateBaseUrl(url) {
    this.baseUrl = url.replace(/\/$/, "");
  }
  setBaseUrl(url) {
    this.baseUrl = url.replace(/\/$/, "");
  }
  async request(path, options = {}) {
    const url = `${this.baseUrl}${path}`;
    const response = await fetch(url, {
      headers: {
        "Content-Type": "application/json",
        ...options.headers
      },
      ...options
    });
    if (!response.ok) {
      const text = await response.text().catch(() => response.statusText);
      throw new Error(`API ${options.method || "GET"} ${path} \u2192 ${response.status}: ${text}`);
    }
    return response.json();
  }
  async health() {
    try {
      const result = await this.request("/api/health");
      return result.status === "ok";
    } catch (e) {
      return false;
    }
  }
  async healthDetails() {
    try {
      return await this.request("/api/health");
    } catch (e) {
      return null;
    }
  }
  async importBook(force = false, bookDir, language) {
    const params = new URLSearchParams({ force: String(force) });
    if (bookDir)
      params.set("book_dir", bookDir);
    if (language)
      params.set("language", language);
    return this.request(`/api/import?${params}`, { method: "POST" });
  }
  /**
   * Stream chat events from /api/chat via SSE.
   * Yields parsed ChatEvent objects.
   */
  async *chatStream(messages, provider, apiKey, bookDir, language) {
    var _a;
    const url = `${this.baseUrl}/api/chat`;
    const body = { messages };
    if (provider)
      body["provider"] = provider;
    if (apiKey)
      body["api_key"] = apiKey;
    if (bookDir)
      body["book_dir"] = bookDir;
    if (language)
      body["language"] = language;
    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body)
    });
    if (!response.ok) {
      const text = await response.text().catch(() => response.statusText);
      throw new Error(`Chat API error ${response.status}: ${text}`);
    }
    if (!response.body) {
      throw new Error("Response body is null");
    }
    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let buffer = "";
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done)
          break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = (_a = lines.pop()) != null ? _a : "";
        for (const line of lines) {
          const trimmed = line.trim();
          if (trimmed.startsWith("data: ")) {
            const jsonStr = trimmed.slice(6);
            if (jsonStr === "[DONE]")
              return;
            try {
              const event = JSON.parse(jsonStr);
              yield event;
              if (event.type === "done")
                return;
            } catch (e) {
            }
          }
        }
      }
    } finally {
      reader.releaseLock();
    }
  }
};

// src/backend.ts
var { spawn } = require("child_process");
var BackendManager = class {
  constructor() {
    this.proc = null;
    this._running = false;
    this.logLines = [];
  }
  /**
   * Start the narrative-os Python server as a subprocess.
   * @param pythonPath Path to Python 3 executable
   * @param bookDir    Book directory (NOS_BOOK_DIR env var)
   */
  async start(pythonPath, bookDir) {
    var _a, _b;
    if (this._running)
      return;
    const env = {
      ...process.env,
      NOS_BOOK_DIR: bookDir || process.cwd(),
      PYTHONUNBUFFERED: "1"
    };
    try {
      this.proc = spawn(
        pythonPath,
        ["-m", "uvicorn", "narrative_os.server:app", "--host", "127.0.0.1", "--port", "8000"],
        {
          env,
          stdio: ["ignore", "pipe", "pipe"],
          detached: false
        }
      );
      this._running = true;
      (_a = this.proc.stdout) == null ? void 0 : _a.on("data", (chunk) => {
        const line = chunk.toString().trim();
        if (line) {
          this.logLines.push(`[OUT] ${line}`);
          if (this.logLines.length > 200)
            this.logLines.shift();
          console.log("[narrative-forge backend]", line);
        }
      });
      (_b = this.proc.stderr) == null ? void 0 : _b.on("data", (chunk) => {
        const line = chunk.toString().trim();
        if (line) {
          this.logLines.push(`[ERR] ${line}`);
          if (this.logLines.length > 200)
            this.logLines.shift();
          console.error("[narrative-forge backend]", line);
        }
      });
      this.proc.on("exit", (code, signal) => {
        console.log(`[narrative-forge backend] exited (code=${code}, signal=${signal})`);
        this._running = false;
        this.proc = null;
      });
      this.proc.on("error", (err) => {
        console.error("[narrative-forge backend] spawn error:", err);
        this._running = false;
        this.proc = null;
      });
    } catch (err) {
      this._running = false;
      this.proc = null;
      throw new Error(`Failed to start backend: ${err}`);
    }
  }
  /**
   * Stop the backend process gracefully.
   */
  async stop() {
    if (!this.proc)
      return;
    return new Promise((resolve) => {
      if (!this.proc) {
        resolve();
        return;
      }
      const timeout = setTimeout(() => {
        var _a;
        (_a = this.proc) == null ? void 0 : _a.kill("SIGKILL");
        resolve();
      }, 5e3);
      this.proc.on("exit", () => {
        clearTimeout(timeout);
        resolve();
      });
      try {
        this.proc.kill("SIGTERM");
      } catch (e) {
        clearTimeout(timeout);
        resolve();
      }
      this._running = false;
    });
  }
  isRunning() {
    return this._running && this.proc !== null;
  }
  getLogs() {
    return [...this.logLines];
  }
  /**
   * Poll /api/health every 500ms until it responds ok or timeout.
   */
  async waitReady(url, timeoutMs = 15e3) {
    const healthUrl = `${url.replace(/\/$/, "")}/api/health`;
    const deadline = Date.now() + timeoutMs;
    while (Date.now() < deadline) {
      try {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 1e3);
        const res = await fetch(healthUrl, { signal: controller.signal }).finally(() => clearTimeout(timeoutId));
        if (res.ok) {
          const body = await res.json();
          if (body.status === "ok")
            return true;
        }
      } catch (e) {
      }
      await new Promise((resolve) => setTimeout(resolve, 500));
    }
    return false;
  }
};

// src/decorations.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
function charColorSolid(name) {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  }
  const h = Math.abs(hash) % 360;
  return `hsl(${h}, 45%, 45%)`;
}
var DashWidget = class extends import_view.WidgetType {
  constructor(charName, color) {
    super();
    this.charName = charName;
    this.color = color;
  }
  toDOM() {
    const span = document.createElement("span");
    span.className = "narrative-dash-widget";
    span.textContent = "\u2014 ";
    span.style.color = this.color;
    span.style.userSelect = "none";
    span.style.fontWeight = "bold";
    span.dataset["char"] = this.charName;
    span.title = this.charName;
    return span;
  }
  eq(other) {
    return other.charName === this.charName && other.color === this.color;
  }
  ignoreEvent() {
    return false;
  }
};
var DIALOGUE_PATTERN = /^\[character:\s*([^\]]+)\]\s*[—–-]\s*/;
var METADATA_PATTERN = /^\[[\w\s-]+:[^\]]+\](\s+\[[\w\s-]+:[^\]]+\])*/;
function buildDecorations(view, colorMap, defaultColors) {
  const builder = new import_state.RangeSetBuilder();
  const { state } = view;
  const cursorLines = /* @__PURE__ */ new Set();
  for (const range of state.selection.ranges) {
    const line = state.doc.lineAt(range.head);
    cursorLines.add(line.number);
  }
  for (const { from, to } of view.visibleRanges) {
    let pos = from;
    while (pos <= to) {
      const line = state.doc.lineAt(pos);
      const lineText = line.text;
      const onCursorLine = cursorLines.has(line.number);
      const dialogueMatch = DIALOGUE_PATTERN.exec(lineText);
      if (dialogueMatch) {
        const charName = dialogueMatch[1].trim();
        const prefixLen = dialogueMatch[0].length;
        const charColorMapEntry = colorMap["character"];
        const color = (charColorMapEntry == null ? void 0 : charColorMapEntry[charName]) || defaultColors.get(charName) || charColorSolid(charName);
        if (!defaultColors.has(charName)) {
          defaultColors.set(charName, charColorSolid(charName));
        }
        if (!onCursorLine) {
          builder.add(
            line.from,
            line.from + prefixLen,
            import_view.Decoration.replace({
              widget: new DashWidget(charName, color)
            })
          );
          const dialogueFrom = line.from + prefixLen;
          const dialogueTo = line.to;
          if (dialogueFrom < dialogueTo) {
            builder.add(
              dialogueFrom,
              dialogueTo,
              import_view.Decoration.mark({
                class: "narrative-dialogue",
                attributes: {
                  style: `border-bottom: 2px solid ${color}; text-decoration: none;`,
                  "data-char": charName,
                  title: charName
                }
              })
            );
          }
        }
        pos = line.to + 1;
        continue;
      }
      if (!onCursorLine && METADATA_PATTERN.test(lineText)) {
        const stripped = lineText.replace(/\[[\w\s-]+:[^\]]+\]\s*/g, "").trim();
        if (stripped.length === 0 && lineText.trim().length > 0) {
          builder.add(
            line.from,
            line.to,
            import_view.Decoration.mark({
              class: "narrative-metadata-hidden"
            })
          );
        }
      }
      pos = line.to + 1;
    }
  }
  return builder.finish();
}
function buildNosPlugin(colors) {
  return [buildNosDecorations(colors)];
}
function buildNosDecorations(colorMap) {
  const charColorMap = colorMap["character"] || {};
  const defaultColors = /* @__PURE__ */ new Map();
  let tooltipEl = null;
  const plugin = import_view.ViewPlugin.fromClass(
    class {
      constructor(view) {
        this.hoverListener = null;
        this.leaveListener = null;
        this.editorDom = null;
        this.decorations = buildDecorations(view, charColorMap, defaultColors);
        this.attachHoverListeners(view);
      }
      update(update) {
        if (update.docChanged || update.viewportChanged || update.selectionSet) {
          this.decorations = buildDecorations(
            update.view,
            charColorMap,
            defaultColors
          );
        }
      }
      destroy() {
        this.removeHoverListeners();
        this.hideTooltip();
      }
      attachHoverListeners(view) {
        this.editorDom = view.dom;
        this.hoverListener = (e) => {
          const target = e.target;
          const charEl = target.closest("[data-char]");
          if (charEl) {
            const charName = charEl.dataset["char"];
            if (charName)
              this.showTooltip(charName, e.clientX, e.clientY);
          } else {
            this.hideTooltip();
          }
        };
        this.leaveListener = () => {
          this.hideTooltip();
        };
        this.editorDom.addEventListener("mousemove", this.hoverListener);
        this.editorDom.addEventListener("mouseleave", this.leaveListener);
      }
      removeHoverListeners() {
        if (!this.editorDom)
          return;
        if (this.hoverListener) {
          this.editorDom.removeEventListener("mousemove", this.hoverListener);
        }
        if (this.leaveListener) {
          this.editorDom.removeEventListener("mouseleave", this.leaveListener);
        }
      }
      showTooltip(name, x, y) {
        if (!tooltipEl) {
          tooltipEl = document.createElement("div");
          tooltipEl.className = "narrative-hover-tooltip";
          document.body.appendChild(tooltipEl);
        }
        tooltipEl.textContent = `Character: ${name}`;
        tooltipEl.style.left = `${x + 12}px`;
        tooltipEl.style.top = `${y - 30}px`;
        tooltipEl.style.display = "block";
      }
      hideTooltip() {
        if (tooltipEl) {
          tooltipEl.style.display = "none";
        }
      }
    },
    {
      decorations: (v) => v.decorations
    }
  );
  return plugin;
}

// src/context-menu.ts
var import_obsidian2 = require("obsidian");

// src/event-modal.ts
var import_obsidian = require("obsidian");
var EventModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
    this.event = {};
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "Add timeline event" });
    new import_obsidian.Setting(contentEl).setName("Title").setDesc("Required \u2014 short name for this event.").addText((text) => {
      text.setPlaceholder("The Siege of Andruil").onChange((v) => {
        this.event.title = v.trim();
      });
      return text;
    });
    const dateRow = contentEl.createDiv({ cls: "narrative-event-date-row" });
    dateRow.createEl("label", { text: "Date", cls: "narrative-event-row-label" });
    const dateFields = dateRow.createDiv({ cls: "narrative-event-row-fields" });
    const yearInput = dateFields.createEl("input", {
      type: "number",
      placeholder: "Year",
      cls: "narrative-event-num-input"
    });
    yearInput.addEventListener("input", () => {
      const v = yearInput.value.trim();
      this.event.year = v ? parseInt(v, 10) : void 0;
    });
    const monthInput = dateFields.createEl("input", {
      type: "number",
      placeholder: "Month",
      cls: "narrative-event-num-input"
    });
    monthInput.addEventListener("input", () => {
      const v = monthInput.value.trim();
      this.event.month = v ? parseInt(v, 10) : void 0;
    });
    const dayInput = dateFields.createEl("input", {
      type: "number",
      placeholder: "Day",
      cls: "narrative-event-num-input"
    });
    dayInput.addEventListener("input", () => {
      const v = dayInput.value.trim();
      this.event.day = v ? parseInt(v, 10) : void 0;
    });
    const timeRow = contentEl.createDiv({ cls: "narrative-event-date-row" });
    timeRow.createEl("label", { text: "Time", cls: "narrative-event-row-label" });
    const timeFields = timeRow.createDiv({ cls: "narrative-event-row-fields" });
    const hourInput = timeFields.createEl("input", {
      type: "number",
      placeholder: "Hour",
      cls: "narrative-event-num-input"
    });
    hourInput.addEventListener("input", () => {
      const v = hourInput.value.trim();
      this.event.hour = v ? parseInt(v, 10) : void 0;
    });
    const minuteInput = timeFields.createEl("input", {
      type: "number",
      placeholder: "Minute",
      cls: "narrative-event-num-input"
    });
    minuteInput.addEventListener("input", () => {
      const v = minuteInput.value.trim();
      this.event.minute = v ? parseInt(v, 10) : void 0;
    });
    new import_obsidian.Setting(contentEl).setName("Location").setDesc("Type a name \u2014 it will be wrapped in [[]] automatically.").addText((text) => {
      text.setPlaceholder("Andruil").onChange((v) => {
        this.event.location = v.trim() ? `[[${v.trim()}]]` : void 0;
      });
      return text;
    });
    new import_obsidian.Setting(contentEl).setName("Characters").setDesc("Comma-separated names \u2014 each will be wrapped in [[]].").addText((text) => {
      text.setPlaceholder("Artur, Sam").onChange((v) => {
        this.event.characters = parseCharacters(v);
      });
      return text;
    });
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Add to timeline").setCta().onClick(() => {
        var _a, _b;
        const title = (_a = this.event.title) == null ? void 0 : _a.trim();
        if (!title) {
          new import_obsidian.Notice("Please enter an event title.");
          return;
        }
        const result = {
          title,
          ...this.event.year !== void 0 && { year: this.event.year },
          ...this.event.month !== void 0 && { month: this.event.month },
          ...this.event.day !== void 0 && { day: this.event.day },
          ...this.event.hour !== void 0 && { hour: this.event.hour },
          ...this.event.minute !== void 0 && { minute: this.event.minute },
          ...this.event.location && { location: this.event.location },
          ...((_b = this.event.characters) == null ? void 0 : _b.length) && { characters: this.event.characters },
          ...this.event.chapterLink && { chapterLink: this.event.chapterLink }
        };
        this.close();
        this.onSubmit(result);
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
function parseCharacters(raw) {
  const names = raw.split(",").map((s) => s.trim()).filter(Boolean);
  return names.length ? names.map((n) => `[[${n}]]`) : void 0;
}

// src/context-menu.ts
var CharacterSuggestModal = class extends import_obsidian2.SuggestModal {
  constructor(app, characters, onChoose) {
    super(app);
    this.characters = characters;
    this.onChoose = onChoose;
    this.setPlaceholder("Type to filter characters...");
  }
  getSuggestions(query) {
    const q = query.toLowerCase();
    return this.characters.filter(
      (c) => c.name.toLowerCase().includes(q)
    );
  }
  renderSuggestion(char, el) {
    el.createEl("div", { text: char.name, cls: "narrative-suggest-name" });
    if (char.description) {
      el.createEl("small", {
        text: char.description.slice(0, 80),
        cls: "narrative-suggest-desc"
      });
    }
  }
  onChooseSuggestion(char) {
    this.onChoose(char);
  }
};
function assignCharacterToSelection(editor, char) {
  if (!editor.somethingSelected()) {
    new import_obsidian2.Notice("Select some text first.");
    return;
  }
  const cursor = editor.getCursor("from");
  const line = editor.getLine(cursor.line);
  const prefix = `[character: ${char.name}] \u2014 `;
  const existingMatch = /^\[character:\s*[^\]]+\]\s*—\s*/.exec(line);
  if (existingMatch) {
    const newLine = prefix + line.slice(existingMatch[0].length);
    editor.setLine(cursor.line, newLine);
    new import_obsidian2.Notice(`Character changed to ${char.name}`);
  } else {
    const selFrom = editor.getCursor("from");
    const selTo = editor.getCursor("to");
    if (selFrom.line !== selTo.line) {
      for (let ln = selFrom.line; ln <= selTo.line; ln++) {
        const lineText = editor.getLine(ln);
        const existingOnLine = /^\[character:\s*[^\]]+\]\s*—\s*/.exec(lineText);
        if (existingOnLine) {
          editor.setLine(ln, prefix + lineText.slice(existingOnLine[0].length));
        } else {
          editor.setLine(ln, prefix + lineText);
        }
      }
      new import_obsidian2.Notice(`Assigned ${char.name} to ${selTo.line - selFrom.line + 1} lines`);
    } else {
      const colOffset = selFrom.ch;
      const before = line.slice(0, colOffset);
      const selected = line.slice(colOffset, selTo.ch);
      const after = line.slice(selTo.ch);
      if (colOffset === 0) {
        editor.setLine(cursor.line, prefix + line);
      } else {
        editor.setLine(cursor.line, before + prefix + selected + after);
      }
      new import_obsidian2.Notice(`Assigned: ${char.name}`);
    }
  }
}
async function addTimelineEntry(plugin, editor) {
  new EventModal(plugin.app, async (event) => {
    const bookRoot = plugin.getCurrentBookRoot();
    if (!bookRoot) {
      new import_obsidian2.Notice("No book found for this file.");
      return;
    }
    const activeFile = plugin.app.workspace.getActiveFile();
    if (!activeFile)
      return;
    const timestamp = Date.now();
    const blockId = `^tl-${timestamp}`;
    const cursor = editor.getCursor();
    const lineText = editor.getLine(cursor.line);
    editor.setLine(cursor.line, lineText + " " + blockId);
    event.chapterLink = `[[${activeFile.basename}#${blockId}]]`;
    await updateTimelineFile(plugin, bookRoot, event);
  }).open();
}
async function updateTimelineFile(plugin, bookRoot, newEvent) {
  const vault = plugin.app.vault;
  const timelinePath = (0, import_obsidian2.normalizePath)(`${bookRoot}/timeline.md`);
  let existing = "";
  try {
    existing = await vault.adapter.read(timelinePath);
  } catch (e) {
  }
  const events = [];
  const lines = existing.split("\n");
  for (const line of lines) {
    if (!line.startsWith("|"))
      continue;
    if (line.includes("---"))
      continue;
    if (/^\|\s*title\s*\|/.test(line))
      continue;
    const cells = line.split("|").map((c) => c.trim());
    if (cells.length < 9)
      continue;
    const title = cells[1];
    if (!title)
      continue;
    const ev = { title };
    const year = parseInt(cells[2], 10);
    if (!isNaN(year))
      ev.year = year;
    const month = parseInt(cells[3], 10);
    if (!isNaN(month))
      ev.month = month;
    const day = parseInt(cells[4], 10);
    if (!isNaN(day))
      ev.day = day;
    const hour = parseInt(cells[5], 10);
    if (!isNaN(hour))
      ev.hour = hour;
    const minute = parseInt(cells[6], 10);
    if (!isNaN(minute))
      ev.minute = minute;
    if (cells[7])
      ev.location = cells[7];
    if (cells[8]) {
      ev.characters = cells[8].split(",").map((s) => s.trim()).filter(Boolean);
    }
    if (cells[9])
      ev.chapterLink = cells[9];
    events.push(ev);
  }
  events.push(newEvent);
  events.sort((a, b) => {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j;
    const av = [
      (_a = a.year) != null ? _a : Infinity,
      (_b = a.month) != null ? _b : Infinity,
      (_c = a.day) != null ? _c : Infinity,
      (_d = a.hour) != null ? _d : Infinity,
      (_e = a.minute) != null ? _e : Infinity
    ];
    const bv = [
      (_f = b.year) != null ? _f : Infinity,
      (_g = b.month) != null ? _g : Infinity,
      (_h = b.day) != null ? _h : Infinity,
      (_i = b.hour) != null ? _i : Infinity,
      (_j = b.minute) != null ? _j : Infinity
    ];
    for (let i = 0; i < av.length; i++) {
      if (av[i] !== bv[i])
        return av[i] - bv[i];
    }
    return 0;
  });
  const header = `| title | year | month | day | hour | minute | location | characters | chapter |`;
  const separator = `|-------|------|-------|-----|------|--------|----------|------------|---------|`;
  const tableRows = events.map((ev) => {
    var _a, _b;
    const location = ev.location ? wrapWikilink(ev.location) : "";
    const characters = ((_a = ev.characters) == null ? void 0 : _a.length) ? ev.characters.map(wrapWikilink).join(", ") : "";
    const cols = [
      ev.title,
      ev.year !== void 0 ? String(ev.year) : "",
      ev.month !== void 0 ? String(ev.month) : "",
      ev.day !== void 0 ? String(ev.day) : "",
      ev.hour !== void 0 ? String(ev.hour) : "",
      ev.minute !== void 0 ? String(ev.minute) : "",
      location,
      characters,
      (_b = ev.chapterLink) != null ? _b : ""
    ];
    return `| ${cols.join(" | ")} |`;
  });
  const content = `# Timeline

${header}
${separator}
${tableRows.join("\n")}
`;
  try {
    if (vault.getAbstractFileByPath(timelinePath)) {
      await vault.adapter.write(timelinePath, content);
    } else {
      await vault.create(timelinePath, content);
    }
    new import_obsidian2.Notice("Timeline updated.");
  } catch (err) {
    new import_obsidian2.Notice(`Failed to update timeline: ${err}`);
  }
}
function wrapWikilink(s) {
  const trimmed = s.trim();
  if (trimmed.startsWith("[[") && trimmed.endsWith("]]"))
    return trimmed;
  return trimmed ? `[[${trimmed}]]` : "";
}
function registerContextMenu(plugin, getCharacters, activateChat) {
  plugin.registerEvent(
    plugin.app.workspace.on(
      "editor-menu",
      (menu, editor) => {
        if (!editor.somethingSelected())
          return;
        if (activateChat) {
          menu.addItem(
            (item) => item.setTitle("Send to chat").setIcon("message-circle").setSection("narrative").onClick(async () => {
              var _a;
              const selection = editor.getSelection();
              if (!selection.trim())
                return;
              const activeFile = plugin.app.workspace.getActiveFile();
              const fileName = (_a = activeFile == null ? void 0 : activeFile.name) != null ? _a : "current file";
              let fileContent = "";
              if (activeFile) {
                try {
                  fileContent = await plugin.app.vault.read(activeFile);
                } catch (e) {
                }
              }
              const message = `[Selected text: "${selection}"]

Context from ${fileName}:
${fileContent.slice(0, 8e3)}

Please analyze this passage.`;
              const chatView = await activateChat();
              if (chatView) {
                chatView.injectMessage(message);
              } else {
                new import_obsidian2.Notice("Could not open chat panel.");
              }
            })
          );
        }
        menu.addItem(
          (item) => item.setTitle("Add to timeline").setIcon("clock").setSection("narrative").onClick(() => {
            void addTimelineEntry(plugin, editor);
          })
        );
        const characters = getCharacters();
        if (characters.length === 0)
          return;
        if (characters.length <= 15) {
          menu.addItem((item) => {
            item.setTitle("Assign character").setIcon("user").setSection("narrative");
            item.onClick(() => {
              new CharacterSuggestModal(
                plugin.app,
                characters,
                (char) => assignCharacterToSelection(editor, char)
              ).open();
            });
          });
          const shortList = characters.slice(0, 8);
          shortList.forEach((char) => {
            menu.addItem(
              (item) => item.setTitle(`  \u2192 ${char.name}`).setIcon("message-square").setSection("narrative-chars").onClick(() => assignCharacterToSelection(editor, char))
            );
          });
          if (characters.length > 8) {
            menu.addItem(
              (item) => item.setTitle("  \u2192 More characters...").setIcon("more-horizontal").setSection("narrative-chars").onClick(() => {
                new CharacterSuggestModal(
                  plugin.app,
                  characters,
                  (char) => assignCharacterToSelection(editor, char)
                ).open();
              })
            );
          }
        } else {
          menu.addItem(
            (item) => item.setTitle("Assign character...").setIcon("user").setSection("narrative").onClick(() => {
              new CharacterSuggestModal(
                plugin.app,
                characters,
                (char) => assignCharacterToSelection(editor, char)
              ).open();
            })
          );
        }
      }
    )
  );
}

// src/sidebar.ts
var import_obsidian3 = require("obsidian");
var _NarrativeSidebarView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.activeTab = "characters";
    this.isLoading = false;
    this.plugin = plugin;
  }
  getViewType() {
    return _NarrativeSidebarView.VIEW_TYPE;
  }
  getDisplayText() {
    return "Narrative Forge";
  }
  getIcon() {
    return "book-open";
  }
  async onOpen() {
    const root = this.containerEl.children[1];
    root.empty();
    root.addClass("narrative-sidebar");
    const header = root.createEl("div", { cls: "narrative-sidebar-header" });
    header.createEl("span", { text: "Narrative Forge", cls: "narrative-sidebar-title" });
    const refreshBtn = header.createEl("button", {
      cls: "narrative-sidebar-refresh",
      title: "Refresh"
    });
    refreshBtn.innerHTML = "&#8635;";
    refreshBtn.addEventListener("click", () => {
      void this.loadActiveTab();
    });
    this.tabBarEl = root.createEl("div", { cls: "narrative-tab-bar" });
    this.renderTabBar();
    this.tabContentEl = root.createEl("div", { cls: "narrative-tab-content" });
    await this.loadActiveTab();
  }
  async onClose() {
  }
  renderTabBar() {
    this.tabBarEl.empty();
    const tabs = [
      { id: "characters", label: "Characters" },
      { id: "chapters", label: "Chapters" },
      { id: "progress", label: "Progress" }
    ];
    tabs.forEach(({ id, label }) => {
      const btn = this.tabBarEl.createEl("button", {
        text: label,
        cls: `narrative-tab-btn ${id === this.activeTab ? "active" : ""}`
      });
      btn.addEventListener("click", () => {
        this.activeTab = id;
        this.renderTabBar();
        void this.loadActiveTab();
      });
    });
  }
  /** Called from main when active book changes — reloads data. */
  async refresh() {
    await this.loadActiveTab();
  }
  /** Called from main when no book found for active file. */
  showNoBook() {
    this.tabContentEl.empty();
    this.tabContentEl.createEl("div", {
      text: "No book found for this file.",
      cls: "narrative-empty"
    });
    this.tabContentEl.createEl("div", {
      text: "Open a file inside a book folder, or create a new book.",
      cls: "narrative-empty-hint"
    });
  }
  async loadActiveTab() {
    if (this.isLoading)
      return;
    this.isLoading = true;
    this.showLoading();
    try {
      switch (this.activeTab) {
        case "characters": {
          const chars = await this.loadCharacters();
          this.renderCharacters(chars);
          break;
        }
        case "chapters": {
          const chapters = await this.loadChapters();
          this.renderChapters(chapters);
          break;
        }
        case "progress": {
          const progress = await this.loadProgress();
          this.renderProgress(progress);
          break;
        }
      }
    } catch (err) {
      this.showError(
        err instanceof Error ? err.message : "Failed to load data"
      );
    } finally {
      this.isLoading = false;
    }
  }
  showLoading() {
    this.tabContentEl.empty();
    this.tabContentEl.createEl("div", {
      text: "Loading...",
      cls: "narrative-loading"
    });
  }
  showError(msg) {
    this.tabContentEl.empty();
    const errDiv = this.tabContentEl.createEl("div", { cls: "narrative-error" });
    errDiv.createEl("div", { text: "Error", cls: "narrative-error-title" });
    errDiv.createEl("div", { text: msg, cls: "narrative-error-msg" });
  }
  // ---------------------------------------------------------------------------
  // Vault readers
  // ---------------------------------------------------------------------------
  async loadCharacters() {
    const bookRoot = this.plugin.getCurrentBookRoot();
    if (!bookRoot)
      return [];
    const folder = this.plugin.app.vault.getAbstractFileByPath(`${bookRoot}/characters`);
    if (!folder)
      return [];
    const files = this.plugin.app.vault.getFiles().filter(
      (f) => f.path.startsWith(`${bookRoot}/characters/`) && f.extension === "md" && !f.name.startsWith("_")
    );
    return files.map((f) => {
      var _a, _b, _c, _d, _e, _f;
      const fm = (_b = (_a = this.plugin.app.metadataCache.getFileCache(f)) == null ? void 0 : _a.frontmatter) != null ? _b : {};
      return {
        name: f.basename,
        description: (_c = fm.description) != null ? _c : "",
        role: (_d = fm.role) != null ? _d : "",
        status: (_e = fm.status) != null ? _e : "",
        appears_in: (_f = fm.appears_in) != null ? _f : []
      };
    });
  }
  async loadChapters() {
    const bookRoot = this.plugin.getCurrentBookRoot();
    if (!bookRoot)
      return [];
    const files = this.plugin.app.vault.getFiles().filter(
      (f) => f.path.startsWith(`${bookRoot}/chapters/`) && f.extension === "md" && !f.name.startsWith("_")
    );
    return files.map((f) => {
      var _a, _b, _c, _d, _e, _f;
      const fm = (_b = (_a = this.plugin.app.metadataCache.getFileCache(f)) == null ? void 0 : _a.frontmatter) != null ? _b : {};
      return {
        title: (_c = fm.title) != null ? _c : f.basename,
        chapter: (_d = fm.chapter) != null ? _d : 0,
        status: (_e = fm.status) != null ? _e : "draft",
        timeline: (_f = fm.timeline) != null ? _f : "",
        location: typeof fm.location === "string" ? fm.location.replace(/\[\[|\]\]/g, "") : "",
        word_target: fm.word_target
      };
    }).sort((a, b) => a.chapter - b.chapter);
  }
  async loadProgress() {
    return this.loadChapters();
  }
  // ---------------------------------------------------------------------------
  // Characters tab
  // ---------------------------------------------------------------------------
  renderCharacters(characters) {
    this.tabContentEl.empty();
    const bookRoot = this.plugin.getCurrentBookRoot();
    if (characters.length === 0) {
      this.tabContentEl.createEl("div", {
        text: "No characters found. Add markdown files to the characters/ folder.",
        cls: "narrative-empty"
      });
      return;
    }
    const list = this.tabContentEl.createEl("ul", { cls: "narrative-char-list" });
    characters.forEach((char) => {
      const item = list.createEl("li", { cls: "narrative-char-item" });
      const dot = item.createEl("span", { cls: "narrative-char-dot" });
      dot.style.backgroundColor = this.getCharColor(char.name);
      const info = item.createEl("div", { cls: "narrative-char-info" });
      info.createEl("div", { text: char.name, cls: "narrative-char-name" });
      const badges = info.createEl("div", { cls: "narrative-char-badges" });
      if (char.role) {
        badges.createEl("span", {
          text: char.role,
          cls: "narrative-badge narrative-badge-role"
        });
      }
      if (char.status) {
        const statusCls = char.status === "dead" ? "narrative-badge-dead" : "narrative-badge-alive";
        badges.createEl("span", {
          text: char.status,
          cls: `narrative-badge ${statusCls}`
        });
      }
      if (char.description) {
        info.createEl("div", {
          text: char.description.slice(0, 80) + (char.description.length > 80 ? "\u2026" : ""),
          cls: "narrative-char-desc"
        });
      }
      item.addEventListener("click", () => {
        if (!bookRoot)
          return;
        const filePath = `${bookRoot}/characters/${char.name}.md`;
        const file = this.plugin.app.vault.getAbstractFileByPath(filePath);
        if (file instanceof import_obsidian3.TFile) {
          void this.plugin.app.workspace.getLeaf().openFile(file);
        }
      });
    });
  }
  getCharColor(name) {
    let hash = 0;
    for (let i = 0; i < name.length; i++) {
      hash = name.charCodeAt(i) + ((hash << 5) - hash);
    }
    const h = Math.abs(hash) % 360;
    return `hsl(${h}, 45%, 45%)`;
  }
  // ---------------------------------------------------------------------------
  // Chapters tab
  // ---------------------------------------------------------------------------
  renderChapters(chapters) {
    this.tabContentEl.empty();
    const bookRoot = this.plugin.getCurrentBookRoot();
    if (chapters.length === 0) {
      this.tabContentEl.createEl("div", {
        text: "No chapters found. Add markdown files to the chapters/ folder.",
        cls: "narrative-empty"
      });
      return;
    }
    const list = this.tabContentEl.createEl("ul", { cls: "narrative-thread-list" });
    chapters.forEach((ch) => {
      const item = list.createEl("li", { cls: "narrative-thread-item" });
      const topRow = item.createEl("div", { cls: "narrative-thread-top" });
      if (ch.chapter > 0) {
        topRow.createEl("span", {
          text: `Ch. ${ch.chapter}`,
          cls: "narrative-progress-ch"
        });
      }
      topRow.createEl("span", { text: ch.title, cls: "narrative-thread-title" });
      topRow.createEl("span", {
        text: ch.status,
        cls: `narrative-badge narrative-badge-${ch.status.toLowerCase()}`
      });
      if (ch.timeline || ch.location) {
        const meta = item.createEl("div", { cls: "narrative-char-meta" });
        if (ch.timeline)
          meta.createEl("span", { text: ch.timeline });
        if (ch.timeline && ch.location)
          meta.appendText(" \xB7 ");
        if (ch.location)
          meta.createEl("span", { text: ch.location });
      }
      item.addEventListener("click", () => {
        if (!bookRoot)
          return;
        const files = this.plugin.app.vault.getFiles().filter(
          (f) => f.path.startsWith(`${bookRoot}/chapters/`) && f.extension === "md" && !f.name.startsWith("_")
        );
        const target = files.find((f) => {
          var _a, _b, _c, _d;
          const fm = (_b = (_a = this.plugin.app.metadataCache.getFileCache(f)) == null ? void 0 : _a.frontmatter) != null ? _b : {};
          return ((_c = fm.chapter) != null ? _c : 0) === ch.chapter && ((_d = fm.title) != null ? _d : f.basename) === ch.title;
        });
        if (target instanceof import_obsidian3.TFile) {
          void this.plugin.app.workspace.getLeaf().openFile(target);
        }
      });
    });
  }
  // ---------------------------------------------------------------------------
  // Progress tab
  // ---------------------------------------------------------------------------
  renderProgress(chapters) {
    this.tabContentEl.empty();
    if (chapters.length === 0) {
      this.tabContentEl.createEl("div", {
        text: "No progress data found.",
        cls: "narrative-empty"
      });
      return;
    }
    const finalCount = chapters.filter((c) => c.status === "final").length;
    const revCount = chapters.filter((c) => c.status === "revision").length;
    const summaryDiv = this.tabContentEl.createEl("div", {
      cls: "narrative-progress-summary"
    });
    summaryDiv.createEl("span", { text: `${finalCount}/${chapters.length} final` });
    if (revCount > 0) {
      summaryDiv.createEl("span", { text: `${revCount} in revision` });
    }
    const list = this.tabContentEl.createEl("ul", { cls: "narrative-progress-list" });
    chapters.forEach((ch) => {
      const item = list.createEl("li", { cls: "narrative-progress-item" });
      const topRow = item.createEl("div", { cls: "narrative-progress-top" });
      topRow.createEl("span", {
        text: ch.chapter > 0 ? `Ch. ${ch.chapter}` : ch.title,
        cls: "narrative-progress-ch"
      });
      topRow.createEl("span", { text: ch.title, cls: "narrative-thread-title" });
      topRow.createEl("span", {
        text: ch.status,
        cls: `narrative-badge narrative-badge-${ch.status.toLowerCase()}`
      });
      if (ch.word_target && ch.word_target > 0) {
        const barWrapper = item.createEl("div", {
          cls: "narrative-progress-bar-wrapper"
        });
        barWrapper.createEl("div", { cls: "narrative-progress-bar" });
        barWrapper.createEl("span", {
          text: `target: ${ch.word_target.toLocaleString()} w`,
          cls: "narrative-progress-pct"
        });
      }
    });
  }
};
var NarrativeSidebarView = _NarrativeSidebarView;
NarrativeSidebarView.VIEW_TYPE = "narrative-sidebar";

// src/chat.ts
var import_obsidian4 = require("obsidian");
var _NarrativeChatView = class extends import_obsidian4.ItemView {
  constructor(leaf, api, plugin) {
    super(leaf);
    this.messages = [];
    this.isStreaming = false;
    this.api = api;
    this.plugin = plugin;
    this.mdComponent = new import_obsidian4.Component();
  }
  getViewType() {
    return _NarrativeChatView.VIEW_TYPE;
  }
  getDisplayText() {
    return "Narrative Chat";
  }
  getIcon() {
    return "message-circle";
  }
  async onOpen() {
    const root = this.containerEl.children[1];
    root.empty();
    root.addClass("narrative-chat");
    this.mdComponent.load();
    const header = root.createEl("div", { cls: "narrative-chat-header" });
    header.createEl("span", { text: "Narrative Chat", cls: "narrative-chat-title" });
    const clearBtn = header.createEl("button", {
      cls: "narrative-chat-clear",
      title: "Clear conversation"
    });
    clearBtn.textContent = "\u2715";
    clearBtn.addEventListener("click", () => this.clearChat());
    this.messagesEl = root.createEl("div", { cls: "narrative-chat-messages" });
    this.appendSystemMessage(
      "Ask anything about your story. The AI uses tools to read files when needed."
    );
    const inputArea = root.createEl("div", { cls: "narrative-chat-input-area" });
    this.inputEl = inputArea.createEl("textarea", {
      cls: "narrative-chat-input",
      attr: { placeholder: "Ask about characters, consistency, plot..." }
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.handleSend();
      }
    });
    const btnRow = inputArea.createEl("div", { cls: "narrative-chat-btn-row" });
    this.sendBtn = btnRow.createEl("button", {
      text: "Send",
      cls: "narrative-chat-send narrative-btn-primary"
    });
    this.sendBtn.addEventListener("click", () => void this.handleSend());
    const ctxIndicator = btnRow.createEl("span", {
      cls: "narrative-chat-context-info"
    });
    ctxIndicator.textContent = "Uses tools to read files";
  }
  async onClose() {
    this.mdComponent.unload();
  }
  // ---------------------------------------------------------------------------
  // Chat logic
  // ---------------------------------------------------------------------------
  clearChat() {
    this.messages = [];
    this.messagesEl.empty();
    this.appendSystemMessage(
      "Conversation cleared. Ask anything about your story."
    );
  }
  getContext() {
    var _a, _b, _c, _d, _e, _f;
    const vaultPath = this.plugin.app.vault.adapter instanceof import_obsidian4.FileSystemAdapter ? this.plugin.app.vault.adapter.getBasePath() : "";
    const view = this.plugin.app.workspace.getActiveViewOfType(import_obsidian4.MarkdownView);
    const relativePath = (_c = (_b = (_a = view == null ? void 0 : view.file) == null ? void 0 : _a.path) != null ? _b : this.plugin.lastActiveMdPath) != null ? _c : "";
    const filePath = vaultPath && relativePath ? `${vaultPath}/${relativePath}` : relativePath;
    return {
      fileContent: (_d = view == null ? void 0 : view.editor.getValue()) != null ? _d : "",
      selection: (_e = view == null ? void 0 : view.editor.getSelection()) != null ? _e : "",
      fileName: (_f = relativePath.split("/").pop()) != null ? _f : "",
      filePath
    };
  }
  /**
   * Pre-fill the chat input with text and send immediately.
   * Called by "Send to chat" context menu item.
   */
  injectMessage(text) {
    if (!this.inputEl)
      return;
    this.inputEl.value = text;
    void this.handleSend();
  }
  async sendMessage(text) {
    console.log("[NOS chat] sendMessage called, isStreaming=", this.isStreaming, "text=", text.slice(0, 30));
    if (!text.trim() || this.isStreaming)
      return;
    this.messages.push({ role: "user", content: text });
    this.appendUserMessage(text);
    this.isStreaming = true;
    this.sendBtn.disabled = true;
    this.sendBtn.textContent = "...";
    const assistantEl = this.appendAssistantMessage("");
    let fullText = "";
    const toolUses = [];
    try {
      const provider = this.plugin.settings.provider === "api" ? "api" : void 0;
      const apiKey = this.plugin.settings.provider === "api" ? this.plugin.settings.apiKey || void 0 : void 0;
      const { messages: apiMessages, bookDir } = await this.buildApiMessages();
      const language = this.plugin.getCurrentBookLanguage();
      console.log("[NOS chat] sending to", this.api.baseUrl, "bookDir=", bookDir, "lang=", language);
      for await (const event of this.api.chatStream(
        apiMessages,
        provider,
        apiKey,
        bookDir,
        language
      )) {
        this.handleChatEvent(event, assistantEl, (text2) => {
          fullText += text2;
          this.updateAssistantMessage(assistantEl, fullText);
        }, toolUses);
      }
      this.messages.push({
        role: "assistant",
        content: fullText,
        toolUses: toolUses.length > 0 ? toolUses : void 0
      });
      if (toolUses.length > 0) {
        this.appendToolSummary(assistantEl, toolUses);
      }
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      this.updateAssistantMessage(
        assistantEl,
        `Error: ${errMsg}

Is the backend running at ${this.plugin.getBackendUrl()}?`
      );
      new import_obsidian4.Notice(`Chat error: ${errMsg}`);
    } finally {
      this.isStreaming = false;
      const indicator = assistantEl.querySelector(".narrative-stream-indicator");
      if (indicator)
        indicator.style.display = "none";
      this.sendBtn.disabled = false;
      this.sendBtn.textContent = "Send";
      this.scrollToBottom();
    }
  }
  /**
   * Build messages for the API — identical to this.messages except the last
   * user message is enriched with the active file path and selection.
   * Also returns the absolute book root directory.
   */
  async buildApiMessages() {
    const msgs = this.messages.map((m) => ({ role: m.role, content: m.content }));
    const vaultBase = this.plugin.app.vault.adapter instanceof import_obsidian4.FileSystemAdapter ? this.plugin.app.vault.adapter.getBasePath() : "";
    let bookRoot = this.plugin.getCurrentBookRoot();
    if (bookRoot == null) {
      const activeFile = this.plugin.app.workspace.getActiveFile();
      if ((activeFile == null ? void 0 : activeFile.extension) === "md") {
        const result = await this.plugin.bookManager.findBook(activeFile.path);
        if (result)
          bookRoot = result.bookRoot;
      }
    }
    const bookDir = vaultBase && bookRoot != null ? bookRoot ? `${vaultBase}/${bookRoot}` : vaultBase : void 0;
    if (msgs.length === 0)
      return { messages: msgs, bookDir };
    const last = msgs[msgs.length - 1];
    if (last.role !== "user")
      return { messages: msgs, bookDir };
    const ctx = this.getContext();
    if (ctx.filePath || ctx.fileName) {
      const parts = [];
      parts.push(`[Active file: ${ctx.filePath || ctx.fileName}]`);
      if (ctx.selection) {
        parts.push(`[Selected text]:
${ctx.selection}`);
      }
      parts.push(last.content);
      msgs[msgs.length - 1] = { role: "user", content: parts.join("\n") };
    }
    return { messages: msgs, bookDir };
  }
  handleChatEvent(event, _el, onText, toolUses) {
    switch (event.type) {
      case "text_delta": {
        const data = event.data;
        if (data.text)
          onText(data.text);
        break;
      }
      case "tool_use": {
        const data = event.data;
        if (data.name) {
          toolUses.push({ name: data.name, input: data.input || {} });
        }
        break;
      }
      case "done":
        break;
      default:
        break;
    }
  }
  async handleSend() {
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    this.inputEl.value = "";
    await this.sendMessage(text);
  }
  // ---------------------------------------------------------------------------
  // DOM helpers
  // ---------------------------------------------------------------------------
  appendSystemMessage(text) {
    const div = this.messagesEl.createEl("div", { cls: "narrative-msg narrative-msg-system" });
    div.createEl("span", { text });
    this.scrollToBottom();
  }
  appendUserMessage(text) {
    const div = this.messagesEl.createEl("div", { cls: "narrative-msg narrative-msg-user" });
    div.createEl("div", { cls: "narrative-msg-label", text: "You" });
    const content = div.createEl("div", { cls: "narrative-msg-content" });
    content.textContent = text;
    this.scrollToBottom();
    return div;
  }
  appendAssistantMessage(text) {
    const div = this.messagesEl.createEl("div", { cls: "narrative-msg narrative-msg-assistant" });
    div.createEl("div", { cls: "narrative-msg-label", text: "Narrative AI" });
    const content = div.createEl("div", { cls: "narrative-msg-content" });
    content.textContent = text;
    const indicator = div.createEl("span", { cls: "narrative-stream-indicator" });
    indicator.textContent = "\u258B";
    this.scrollToBottom();
    return div;
  }
  updateAssistantMessage(el, text) {
    const content = el.querySelector(".narrative-msg-content");
    if (content) {
      content.empty();
      try {
        void import_obsidian4.MarkdownRenderer.renderMarkdown(text, content, "", this.mdComponent);
      } catch (e) {
        content.textContent = text;
      }
    }
    this.scrollToBottom();
  }
  appendToolSummary(el, toolUses) {
    const details = el.createEl("details", { cls: "narrative-tool-details" });
    details.createEl("summary", { text: `${toolUses.length} tool call(s) used` });
    toolUses.forEach((t) => {
      const toolDiv = details.createEl("div", { cls: "narrative-tool-item" });
      toolDiv.createEl("code", { text: t.name });
      const inputStr = JSON.stringify(t.input, null, 2);
      if (inputStr !== "{}") {
        const pre = toolDiv.createEl("pre", { cls: "narrative-tool-input" });
        pre.textContent = inputStr;
      }
    });
  }
  scrollToBottom() {
    this.messagesEl.scrollTop = this.messagesEl.scrollHeight;
  }
};
var NarrativeChatView = _NarrativeChatView;
NarrativeChatView.VIEW_TYPE = "narrative-chat";

// src/settings.ts
var import_obsidian5 = require("obsidian");
var DEFAULT_SETTINGS = {
  backendMode: "external",
  externalUrl: "http://localhost:8000",
  defaultBackendUrl: "http://localhost:8000",
  pythonPath: "python3",
  bookDir: "",
  provider: "cli",
  apiKey: "",
  autoImport: true
};
var NarrativeSettingTab = class extends import_obsidian5.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Narrative Forge Settings" });
    containerEl.createEl("h3", { text: "Backend" });
    new import_obsidian5.Setting(containerEl).setName("Backend mode").setDesc("How to connect to the narrative-forge Python backend.").addDropdown(
      (drop) => drop.addOption("external", "External URL (backend runs separately)").addOption("managed", "Managed (plugin starts/stops backend)").setValue(this.plugin.settings.backendMode).onChange(async (value) => {
        this.plugin.settings.backendMode = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.backendMode === "external") {
      new import_obsidian5.Setting(containerEl).setName("Backend URL").setDesc("URL of the running narrative-forge server (e.g. http://localhost:8000).").addText(
        (text) => text.setPlaceholder("http://localhost:8000").setValue(this.plugin.settings.externalUrl).onChange(async (value) => {
          this.plugin.settings.externalUrl = value.trim();
          await this.plugin.saveSettings();
          this.plugin.api.updateBaseUrl(this.plugin.getBackendUrl());
        })
      );
    } else {
      new import_obsidian5.Setting(containerEl).setName("Python path").setDesc("Path to Python 3 executable (or 'python3').").addText(
        (text) => text.setPlaceholder("python3").setValue(this.plugin.settings.pythonPath).onChange(async (value) => {
          this.plugin.settings.pythonPath = value.trim();
          await this.plugin.saveSettings();
        })
      );
      new import_obsidian5.Setting(containerEl).setName("Book directory").setDesc(
        "Path to the directory containing .nos files. Leave empty to use vault root."
      ).addText(
        (text) => text.setPlaceholder("/path/to/book (empty = vault root)").setValue(this.plugin.settings.bookDir).onChange(async (value) => {
          this.plugin.settings.bookDir = value.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian5.Setting(containerEl).setName("Default backend URL").setDesc(
      "Fallback URL used when the active file is not inside a book folder with .narrative-book.json."
    ).addText(
      (text) => text.setPlaceholder("http://localhost:8000").setValue(this.plugin.settings.defaultBackendUrl).onChange(async (value) => {
        this.plugin.settings.defaultBackendUrl = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian5.Setting(containerEl).setName("Test connection").setDesc("Check if the backend is reachable.").addButton(
      (btn) => btn.setButtonText("Test").setCta().onClick(async () => {
        btn.setButtonText("Testing...");
        btn.setDisabled(true);
        try {
          const healthy = await this.plugin.api.health();
          if (healthy) {
            new import_obsidian5.Notice("Narrative Forge: Connected successfully!");
            btn.setButtonText("Connected");
          } else {
            new import_obsidian5.Notice("Narrative Forge: Backend unreachable.");
            btn.setButtonText("Failed");
          }
        } catch (e) {
          new import_obsidian5.Notice("Narrative Forge: Connection error.");
          btn.setButtonText("Error");
        } finally {
          btn.setDisabled(false);
          setTimeout(() => btn.setButtonText("Test"), 3e3);
        }
      })
    );
    containerEl.createEl("h3", { text: "LLM Provider" });
    new import_obsidian5.Setting(containerEl).setName("Provider").setDesc("Which LLM to use for AI features.").addDropdown(
      (drop) => drop.addOption("cli", "Claude CLI (uses local Claude subscription)").addOption("api", "Claude API (requires API key)").setValue(this.plugin.settings.provider).onChange(async (value) => {
        this.plugin.settings.provider = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.provider === "api") {
      new import_obsidian5.Setting(containerEl).setName("Anthropic API key").setDesc("Your Anthropic API key (sk-ant-...).").addText((text) => {
        text.setPlaceholder("sk-ant-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
          this.plugin.settings.apiKey = value.trim();
          await this.plugin.saveSettings();
        });
        text.inputEl.type = "password";
        return text;
      });
    }
    containerEl.createEl("h3", { text: "Import" });
    new import_obsidian5.Setting(containerEl).setName("Auto-import on save").setDesc(
      "Automatically trigger book import when a .nos or .md file is saved."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoImport).onChange(async (value) => {
        this.plugin.settings.autoImport = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Books" });
    new import_obsidian5.Setting(containerEl).setName("Create new book").setDesc(
      "Create a new book folder with .narrative-book.json marker and default structure."
    ).addButton(
      (btn) => btn.setButtonText("Create new book...").onClick(() => {
        const cmd = this.app.commands;
        if (cmd) {
          cmd.executeCommandById("narrative-forge:create-book");
        }
      })
    );
    containerEl.createEl("h3", { text: "About" });
    const infoDiv = containerEl.createEl("div", { cls: "narrative-settings-info" });
    infoDiv.createEl("p", {
      text: "Narrative Forge v0.4.0 \u2014 AI-powered writing assistant for fiction authors."
    });
    infoDiv.createEl("p", {
      text: "Start the backend with: uvicorn narrative_os.server:app --reload",
      cls: "narrative-settings-code"
    });
  }
};

// src/book.ts
var import_obsidian6 = require("obsidian");
var BOOK_MARKER = ".narrative-book.json";
var BookManager = class {
  constructor(app) {
    this.app = app;
  }
  // ---------------------------------------------------------------------------
  // Book detection
  // ---------------------------------------------------------------------------
  /**
   * Walk up from filePath until we find .narrative-book.json.
   * Returns { config, bookRoot } or null if not inside any book.
   */
  async readMarker(markerPath) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m;
    try {
      const raw = await this.app.vault.adapter.read(markerPath);
      const config = JSON.parse(raw);
      return {
        title: (_a = config.title) != null ? _a : "Untitled",
        author: (_b = config.author) != null ? _b : "",
        backendUrl: (_c = config.backendUrl) != null ? _c : "http://localhost:8000",
        folders: {
          chapters: (_e = (_d = config.folders) == null ? void 0 : _d.chapters) != null ? _e : "chapters",
          characters: (_g = (_f = config.folders) == null ? void 0 : _f.characters) != null ? _g : "characters",
          locations: (_i = (_h = config.folders) == null ? void 0 : _h.locations) != null ? _i : "locations",
          world: (_k = (_j = config.folders) == null ? void 0 : _j.world) != null ? _k : "world",
          notes: (_m = (_l = config.folders) == null ? void 0 : _l.notes) != null ? _m : "notes"
        }
      };
    } catch (e) {
      return null;
    }
  }
  async findBook(filePath) {
    const parts = filePath.split("/");
    parts.pop();
    while (parts.length > 0) {
      const dir = parts.join("/");
      const markerPath = (0, import_obsidian6.normalizePath)(`${dir}/${BOOK_MARKER}`);
      if (await this.app.vault.adapter.exists(markerPath)) {
        const config = await this.readMarker(markerPath);
        if (config)
          return { config, bookRoot: dir };
      }
      parts.pop();
    }
    if (await this.app.vault.adapter.exists(BOOK_MARKER)) {
      const config = await this.readMarker(BOOK_MARKER);
      if (config)
        return { config, bookRoot: "" };
    }
    return null;
  }
  // ---------------------------------------------------------------------------
  // Chapter metadata sync
  // ---------------------------------------------------------------------------
  /**
   * Parse a chapter file's frontmatter and inline scene metadata,
   * then ensure character/location notes exist and are up to date.
   *
   * One-directional: chapter → character/location notes.
   */
  async syncChapterMetadata(file, bookRoot, config) {
    const content = await this.app.vault.read(file);
    const chapterLink = `[[${file.basename}]]`;
    const frontmatterMatch = /^---\r?\n([\s\S]*?)\r?\n---/.exec(content);
    const characterNames = [];
    const locationNames = [];
    if (frontmatterMatch) {
      const yaml = frontmatterMatch[1];
      const charsBlockMatch = /^characters:\s*\r?\n((?:[ \t]+-[^\n]*\n?)*)/m.exec(yaml);
      if (charsBlockMatch) {
        const lines = charsBlockMatch[1].split("\n");
        for (const line of lines) {
          const m2 = /^\s*-\s*["']?\[\[([^\]]+)\]\]["']?/.exec(line);
          if (m2)
            characterNames.push(m2[1].trim());
        }
      }
      const povMatch = /^pov:\s*["']?\[\[([^\]]+)\]\]["']?/m.exec(yaml);
      if (povMatch) {
        const name = povMatch[1].trim();
        if (!characterNames.includes(name))
          characterNames.push(name);
      }
      const locMatch = /^location:\s*["']?\[\[([^\]]+)\]\]["']?/m.exec(yaml);
      if (locMatch)
        locationNames.push(locMatch[1].trim());
    }
    const inlineLocRe = /^location::\s*\[\[([^\]]+)\]\]/gm;
    let m;
    while ((m = inlineLocRe.exec(content)) !== null) {
      const name = m[1].trim();
      if (!locationNames.includes(name))
        locationNames.push(name);
    }
    const inlineCharRe = /^characters?::\s*(.*)/gm;
    while ((m = inlineCharRe.exec(content)) !== null) {
      const raw = m[1];
      const linkRe = /\[\[([^\]]+)\]\]/g;
      let lm;
      while ((lm = linkRe.exec(raw)) !== null) {
        const name = lm[1].trim();
        if (!characterNames.includes(name))
          characterNames.push(name);
      }
    }
    const vault = this.app.vault;
    const rootPrefix = bookRoot ? `${bookRoot}/` : "";
    for (const name of characterNames) {
      const notePath = (0, import_obsidian6.normalizePath)(
        `${rootPrefix}${config.folders.characters}/${name}.md`
      );
      await this.ensureNote(vault, notePath, "character", chapterLink);
    }
    for (const name of locationNames) {
      const notePath = (0, import_obsidian6.normalizePath)(
        `${rootPrefix}${config.folders.locations}/${name}.md`
      );
      await this.ensureNote(vault, notePath, "location", chapterLink);
    }
  }
  // ---------------------------------------------------------------------------
  // Private helpers
  // ---------------------------------------------------------------------------
  /** Strip [[ and ]] from a wikilink string. */
  parseWikilink(s) {
    return s.replace(/^\[\[/, "").replace(/\]\]$/, "").trim();
  }
  /**
   * Ensure a character/location note exists.
   * If it doesn't, create it with default frontmatter.
   * Either way, make sure chapterLink is in appears_in.
   */
  async ensureNote(vault, notePath, type, chapterLink) {
    const existing = vault.getAbstractFileByPath(notePath);
    if (!(existing instanceof import_obsidian6.TFile)) {
      const folder = notePath.substring(0, notePath.lastIndexOf("/"));
      if (folder && !vault.getAbstractFileByPath(folder)) {
        await vault.createFolder(folder).catch(() => {
        });
      }
      const initialContent = this.buildNoteContent(type, [chapterLink]);
      await vault.create(notePath, initialContent).catch(() => {
      });
      return;
    }
    const content = await vault.read(existing);
    const updated = this.addToAppearsIn(content, chapterLink, type);
    if (updated !== content) {
      await vault.modify(existing, updated);
    }
  }
  buildNoteContent(type, appearsIn) {
    const list = appearsIn.map((l) => `  - "${l}"`).join("\n");
    return `---
type: ${type}
aliases: []
appears_in:
${list}
description: ""
---
`;
  }
  /**
   * Add chapterLink to the appears_in YAML list if not already present.
   * Handles both plain and quoted wikilink formats.
   */
  addToAppearsIn(content, chapterLink, type) {
    const basename = chapterLink.replace(/^\[\[/, "").replace(/\]\]$/, "");
    if (content.includes(`[[${basename}]]`) || content.includes(`"[[${basename}]]"`)) {
      return content;
    }
    const appearsInRe = /^(appears_in:\s*\r?\n)((?:[ \t]+-[^\n]*\n?)*)/m;
    const match = appearsInRe.exec(content);
    if (match) {
      const newEntry = `  - "${chapterLink}"
`;
      return content.replace(
        appearsInRe,
        `$1${match[2]}${newEntry}`
      );
    }
    const emptyListRe = /^appears_in:\s*(\[\])?\s*$/m;
    if (emptyListRe.test(content)) {
      return content.replace(
        emptyListRe,
        `appears_in:
  - "${chapterLink}"`
      );
    }
    const closingRe = /^(---\r?\n[\s\S]*?)(^---)/m;
    if (closingRe.test(content)) {
      return content.replace(
        closingRe,
        `$1appears_in:
  - "${chapterLink}"
$2`
      );
    }
    return content;
  }
};

// src/timeline.ts
var import_obsidian7 = require("obsidian");
var _NarrativeTimelineView = class extends import_obsidian7.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return _NarrativeTimelineView.VIEW_TYPE;
  }
  getDisplayText() {
    return "Timeline";
  }
  getIcon() {
    return "clock";
  }
  async onOpen() {
    await this.refresh();
  }
  async refresh() {
    const { containerEl } = this;
    containerEl.empty();
    const container = containerEl.createDiv({ cls: "narrative-timeline-container" });
    const toolbar = container.createDiv({ cls: "narrative-timeline-toolbar" });
    const refreshBtn = toolbar.createEl("button", {
      text: "Refresh",
      cls: "narrative-btn-secondary"
    });
    refreshBtn.addEventListener("click", () => void this.refresh());
    const bookRoot = this.plugin.getCurrentBookRoot();
    if (!bookRoot) {
      toolbar.createEl("span", {
        text: "No book active",
        cls: "narrative-timeline-count"
      });
      const canvasWrapper2 = container.createDiv({ cls: "narrative-timeline-canvas-wrapper" });
      const empty = canvasWrapper2.createDiv({ cls: "narrative-timeline-empty" });
      empty.createEl("div", { text: "Open a file inside a book to see its timeline." });
      return;
    }
    const events = await this.loadEvents();
    toolbar.createEl("span", {
      text: `${events.length} event${events.length !== 1 ? "s" : ""}`,
      cls: "narrative-timeline-count"
    });
    const canvasWrapper = container.createDiv({ cls: "narrative-timeline-canvas-wrapper" });
    if (events.length === 0) {
      const empty = canvasWrapper.createDiv({ cls: "narrative-timeline-empty" });
      empty.createEl("div", { text: "No timeline events yet." });
      empty.createEl("div", {
        text: 'Right-click text \u2192 "Add to timeline".',
        cls: "narrative-timeline-empty-hint"
      });
      return;
    }
    this.renderTimeline(events, canvasWrapper);
  }
  // ---------------------------------------------------------------------------
  // Load events from timeline.md
  // ---------------------------------------------------------------------------
  async loadEvents() {
    const bookRoot = this.plugin.getCurrentBookRoot();
    if (!bookRoot)
      return [];
    const timelinePath = (0, import_obsidian7.normalizePath)(`${bookRoot}/timeline.md`);
    let content = "";
    try {
      content = await this.plugin.app.vault.adapter.read(timelinePath);
    } catch (e) {
      return [];
    }
    const events = [];
    const lines = content.split("\n");
    for (const line of lines) {
      if (!line.startsWith("|"))
        continue;
      if (line.includes("---"))
        continue;
      if (/^\|\s*title\s*\|/.test(line))
        continue;
      const cells = line.split("|").map((c) => c.trim());
      if (cells.length < 9)
        continue;
      const title = cells[1];
      if (!title)
        continue;
      const ev = { title };
      const year = parseInt(cells[2], 10);
      if (!isNaN(year))
        ev.year = year;
      const month = parseInt(cells[3], 10);
      if (!isNaN(month))
        ev.month = month;
      const day = parseInt(cells[4], 10);
      if (!isNaN(day))
        ev.day = day;
      const hour = parseInt(cells[5], 10);
      if (!isNaN(hour))
        ev.hour = hour;
      const minute = parseInt(cells[6], 10);
      if (!isNaN(minute))
        ev.minute = minute;
      if (cells[7])
        ev.location = cells[7];
      if (cells[8]) {
        ev.characters = cells[8].split(",").map((s) => s.trim()).filter(Boolean);
      }
      if (cells[9])
        ev.chapterLink = cells[9];
      events.push(ev);
    }
    return events;
  }
  // ---------------------------------------------------------------------------
  // Render timeline
  // ---------------------------------------------------------------------------
  renderTimeline(events, canvasWrapper) {
    const CARD_WIDTH = 180;
    const CARD_SPACING = 220;
    const START_X = 60;
    const CANVAS_HEIGHT = 480;
    const LINE_Y = 240;
    const STEM_LENGTH = 20;
    const CARD_HEIGHT_APPROX = 110;
    const canvasWidth = Math.max(
      canvasWrapper.clientWidth || 800,
      START_X + events.length * CARD_SPACING + 120
    );
    const canvas = canvasWrapper.createDiv({ cls: "narrative-timeline-canvas" });
    canvas.style.position = "relative";
    canvas.style.width = `${canvasWidth}px`;
    canvas.style.height = `${CANVAS_HEIGHT}px`;
    const line = canvas.createDiv({ cls: "narrative-timeline-line" });
    line.style.top = `${LINE_Y}px`;
    events.forEach((ev, idx) => {
      var _a, _b;
      const above = idx % 2 === 0;
      const cx = START_X + idx * CARD_SPACING;
      const dot = canvas.createDiv({ cls: "narrative-event-dot" });
      dot.style.left = `${cx}px`;
      dot.style.top = `${LINE_Y}px`;
      dot.style.transform = "translate(-50%, -50%)";
      const stem = canvas.createDiv({ cls: "narrative-event-stem" });
      stem.style.left = `${cx}px`;
      if (above) {
        stem.style.top = `${LINE_Y - STEM_LENGTH}px`;
        stem.style.height = `${STEM_LENGTH}px`;
      } else {
        stem.style.top = `${LINE_Y}px`;
        stem.style.height = `${STEM_LENGTH}px`;
      }
      const cardLeft = cx - CARD_WIDTH / 2;
      const cardTop = above ? LINE_Y - STEM_LENGTH - CARD_HEIGHT_APPROX : LINE_Y + STEM_LENGTH;
      const card = canvas.createDiv({ cls: "narrative-event-card" });
      card.style.left = `${cardLeft}px`;
      card.style.top = `${cardTop}px`;
      card.style.width = `${CARD_WIDTH}px`;
      const firstChar = (_a = ev.characters) == null ? void 0 : _a[0];
      const borderColor = firstChar ? charColor(stripWikilink(firstChar)) : "#7b9ab8";
      card.style.borderLeftColor = borderColor;
      card.createDiv({ text: ev.title, cls: "narrative-event-card-title" });
      const dateStr = formatEventDate(ev);
      if (dateStr) {
        card.createDiv({ text: dateStr, cls: "narrative-event-card-date" });
      }
      if (ev.location) {
        card.createDiv({
          text: `\u{1F4CD} ${stripWikilink(ev.location)}`,
          cls: "narrative-event-card-meta"
        });
      }
      if ((_b = ev.characters) == null ? void 0 : _b.length) {
        const names = ev.characters.map(stripWikilink).join(", ");
        card.createDiv({
          text: `\u{1F464} ${names}`,
          cls: "narrative-event-card-meta"
        });
      }
      card.addEventListener("click", () => {
        if (ev.chapterLink) {
          const inner = ev.chapterLink.replace(/^\[\[|\]\]$/g, "");
          const [filePath, blockRef] = inner.split("#");
          const file = this.plugin.app.metadataCache.getFirstLinkpathDest(filePath, "");
          if (file) {
            const leaf = this.plugin.app.workspace.getLeaf();
            void leaf.openFile(file, {
              eState: { subpath: blockRef ? "#" + blockRef : "" }
            });
          }
        }
      });
    });
  }
};
var NarrativeTimelineView = _NarrativeTimelineView;
NarrativeTimelineView.VIEW_TYPE = "narrative-timeline";
function charColor(name) {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  }
  const h = Math.abs(hash) % 360;
  return `hsl(${h}, 45%, 55%)`;
}
function formatEventDate(ev) {
  var _a, _b;
  const parts = [];
  if (ev.year !== void 0)
    parts.push(`Year ${ev.year}`);
  if (ev.month !== void 0) {
    const months = [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    ];
    parts.push((_a = months[ev.month - 1]) != null ? _a : `M${ev.month}`);
  }
  if (ev.day !== void 0)
    parts.push(String(ev.day));
  if (ev.hour !== void 0) {
    parts.push(
      `${String(ev.hour).padStart(2, "0")}:${String((_b = ev.minute) != null ? _b : 0).padStart(2, "0")}`
    );
  }
  return parts.join(" ");
}
function stripWikilink(s) {
  return s.replace(/^\[\[/, "").replace(/\]\]$/, "").replace(/#.*$/, "").trim();
}

// src/session.ts
var import_obsidian8 = require("obsidian");
function countWords(text) {
  return text.trim() === "" ? 0 : text.trim().split(/\s+/).length;
}
function fmtTime(seconds) {
  const m = Math.floor(seconds / 60).toString().padStart(2, "0");
  const s = (seconds % 60).toString().padStart(2, "0");
  return `${m}:${s}`;
}
var SessionModal = class extends import_obsidian8.Modal {
  constructor(app, isActive, written, deleted, onStart, onStop) {
    super(app);
    this.minutes = 25;
    this.isActive = isActive;
    this.written = written;
    this.deleted = deleted;
    this.onStart = onStart;
    this.onStop = onStop;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Writing session" });
    if (this.isActive) {
      contentEl.createEl("p", {
        text: `Session in progress: +${this.written} written, -${this.deleted} deleted.`
      });
      new import_obsidian8.Setting(contentEl).addButton(
        (btn) => btn.setButtonText("Stop session").setWarning().onClick(() => {
          this.onStop();
          this.close();
        })
      );
      return;
    }
    new import_obsidian8.Setting(contentEl).setName("Duration (minutes)").addSlider(
      (sl) => sl.setLimits(5, 120, 5).setValue(this.minutes).setDynamicTooltip().onChange((v) => {
        this.minutes = v;
      })
    );
    new import_obsidian8.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Start").setCta().onClick(() => {
        this.onStart(this.minutes);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var WritingSession = class {
  constructor(plugin) {
    this.state = {
      active: false,
      durationSec: 0,
      remainingSec: 0,
      written: 0,
      deleted: 0,
      lastWordCount: 0
    };
    this.ticker = null;
    this.plugin = plugin;
    const item = plugin.addStatusBarItem();
    item.addClass("narrative-session-bar");
    item.style.cursor = "pointer";
    this.statusEl = item;
    this.renderIdle();
    item.addEventListener("click", () => this.openModal());
    plugin.registerEvent(
      plugin.app.workspace.on("editor-change", (editor) => {
        if (!this.state.active)
          return;
        const current = countWords(editor.getValue());
        const delta = current - this.state.lastWordCount;
        if (delta > 0)
          this.state.written += delta;
        else if (delta < 0)
          this.state.deleted += Math.abs(delta);
        this.state.lastWordCount = current;
        this.renderActive();
      })
    );
  }
  openModal() {
    new SessionModal(
      this.plugin.app,
      this.state.active,
      this.state.written,
      this.state.deleted,
      (minutes) => this.start(minutes),
      () => this.stop()
    ).open();
  }
  start(minutes) {
    var _a;
    const editor = (_a = this.plugin.app.workspace.activeEditor) == null ? void 0 : _a.editor;
    this.state = {
      active: true,
      durationSec: minutes * 60,
      remainingSec: minutes * 60,
      written: 0,
      deleted: 0,
      lastWordCount: editor ? countWords(editor.getValue()) : 0
    };
    this.ticker = setInterval(() => this.tick(), 1e3);
    this.renderActive();
  }
  stop() {
    if (this.ticker) {
      clearInterval(this.ticker);
      this.ticker = null;
    }
    this.state.active = false;
    this.renderIdle();
  }
  tick() {
    this.state.remainingSec -= 1;
    if (this.state.remainingSec <= 0) {
      this.stop();
      this.statusEl.setText(`\u2705 Done! +${this.state.written} / -${this.state.deleted}`);
      return;
    }
    this.renderActive();
  }
  renderIdle() {
    this.statusEl.setText("\u{1F4D6}");
    this.statusEl.setAttr("title", "Start writing session");
    this.statusEl.removeClass("narrative-session-active");
  }
  renderActive() {
    const { remainingSec, written, deleted } = this.state;
    this.statusEl.setText(
      `\u{1F4D6} ${fmtTime(remainingSec)}  +${written} / -${deleted}`
    );
    this.statusEl.setAttr("title", "Writing session active \u2014 click to stop");
    this.statusEl.addClass("narrative-session-active");
  }
  destroy() {
    this.stop();
  }
};

// src/main.ts
var CreateBookModal = class extends import_obsidian9.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.title = "";
    this.folderName = "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Create new book" });
    new import_obsidian9.Setting(contentEl).setName("Book title").setDesc("The display title of your book.").addText(
      (text) => text.setPlaceholder("My Fantasy Novel").onChange((v) => {
        this.title = v;
        if (!this.folderName || this.folderName === this.slugify(this.title.slice(0, -1))) {
          this.folderName = this.slugify(v);
        }
      })
    );
    new import_obsidian9.Setting(contentEl).setName("Folder name").setDesc("Folder that will be created in the vault root.").addText(
      (text) => text.setPlaceholder("my-fantasy-novel").onChange((v) => {
        this.folderName = v;
      })
    );
    new import_obsidian9.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Create").setCta().onClick(async () => {
        const title = this.title.trim();
        const folder = this.folderName.trim() || this.slugify(title);
        if (!title) {
          new import_obsidian9.Notice("Please enter a book title.");
          return;
        }
        this.close();
        this.onSubmit(title, folder || title);
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
  slugify(s) {
    return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  }
};
var NarrativePlugin = class extends import_obsidian9.Plugin {
  constructor() {
    super(...arguments);
    this.cachedCharacters = [];
    this.autoImportDebounceMap = /* @__PURE__ */ new Map();
    this.currentBookRoot = null;
    this.currentBookLanguage = "uk";
    this.lastActiveMdPath = null;
  }
  // last focused .md file path (vault-relative)
  getCurrentBookRoot() {
    return this.currentBookRoot;
  }
  getCurrentBookLanguage() {
    return this.currentBookLanguage;
  }
  async onload() {
    console.log("[Narrative Forge] Loading plugin...");
    await this.loadSettings();
    this.api = new NarrativeAPI(this.getBackendUrl());
    this.backend = new BackendManager();
    this.bookManager = new BookManager(this.app);
    if (this.settings.backendMode === "managed") {
      const bookDir = this.settings.bookDir || this.app.vault.adapter.basePath || ".";
      try {
        await this.backend.start(this.settings.pythonPath, bookDir);
        new import_obsidian9.Notice("Narrative Forge: Starting backend...");
        const ready = await this.backend.waitReady(this.getBackendUrl(), 15e3);
        if (ready) {
          new import_obsidian9.Notice("Narrative Forge: Backend ready.");
        } else {
          new import_obsidian9.Notice("Narrative Forge: Backend may not be ready \u2014 check logs.");
        }
      } catch (err) {
        new import_obsidian9.Notice(`Narrative Forge: Failed to start backend \u2014 ${err}`);
        console.error("[Narrative Forge] Backend start error:", err);
      }
    }
    this.registerEditorExtension(buildNosPlugin({}));
    registerContextMenu(
      this,
      () => this.cachedCharacters,
      () => this.activateChatAndGetView()
    );
    this.registerView(
      NarrativeSidebarView.VIEW_TYPE,
      (leaf) => new NarrativeSidebarView(leaf, this)
    );
    this.registerView(
      NarrativeChatView.VIEW_TYPE,
      (leaf) => new NarrativeChatView(leaf, this.api, this)
    );
    this.registerView(
      NarrativeTimelineView.VIEW_TYPE,
      (leaf) => new NarrativeTimelineView(leaf, this)
    );
    this.writingSession = new WritingSession(this);
    this.addRibbonIcon("book-open", "Narrative Forge Sidebar", () => {
      void this.activateSidebar();
    });
    this.addRibbonIcon("message-circle", "Narrative Forge Chat", () => {
      void this.activateChat();
    });
    this.addRibbonIcon("clock", "Narrative Timeline", () => {
      void this.activateTimeline();
    });
    this.addCommand({
      id: "import-book",
      name: "Import book",
      callback: () => void this.runImport()
    });
    this.addCommand({
      id: "open-chat",
      name: "Open Chat",
      callback: () => void this.activateChat()
    });
    this.addCommand({
      id: "open-sidebar",
      name: "Open Sidebar",
      callback: () => void this.activateSidebar()
    });
    this.addCommand({
      id: "test-connection",
      name: "Test backend connection",
      callback: () => void this.testConnection()
    });
    this.addCommand({
      id: "create-book",
      name: "Create new book",
      callback: () => void this.createNewBook()
    });
    this.addCommand({
      id: "open-timeline",
      name: "Open Timeline",
      callback: () => void this.activateTimeline()
    });
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        if (file instanceof import_obsidian9.TFile) {
          void this.onActiveFileChange(file);
        }
      })
    );
    if (this.settings.autoImport) {
      this.registerAutoImport();
    }
    this.addSettingTab(new NarrativeSettingTab(this.app, this));
    void this.reloadCharacterCache();
    this.app.workspace.onLayoutReady(() => {
      void this.startupReindex();
    });
    console.log("[Narrative Forge] Plugin loaded.");
  }
  async onunload() {
    console.log("[Narrative Forge] Unloading plugin...");
    if (this.settings.backendMode === "managed") {
      await this.backend.stop();
    }
    for (const timer of this.autoImportDebounceMap.values()) {
      clearTimeout(timer);
    }
    this.autoImportDebounceMap.clear();
  }
  // ---------------------------------------------------------------------------
  // Active file → book detection
  // ---------------------------------------------------------------------------
  async onActiveFileChange(file) {
    var _a;
    if (file.extension !== "md")
      return;
    this.lastActiveMdPath = file.path;
    const result = await this.bookManager.findBook(file.path);
    const sidebar = this.getSidebarView();
    if (result) {
      this.currentBookRoot = result.bookRoot;
      this.currentBookLanguage = (_a = result.config["language"]) != null ? _a : "uk";
      this.api.setBaseUrl(result.config.backendUrl);
      void this.reloadCharacterCache();
      if (sidebar)
        void sidebar.refresh();
    } else {
      if (sidebar)
        sidebar.showNoBook();
    }
  }
  /** Returns absolute filesystem path to the current book root, or undefined. */
  getAbsoluteBookDir() {
    const bookRoot = this.currentBookRoot;
    if (bookRoot == null)
      return void 0;
    const adapter = this.app.vault.adapter;
    if (!(adapter instanceof import_obsidian9.FileSystemAdapter))
      return void 0;
    const base = adapter.getBasePath();
    return bookRoot ? `${base}/${bookRoot}` : base;
  }
  async reloadCharacterCache() {
    const bookRoot = this.currentBookRoot;
    if (!bookRoot) {
      this.cachedCharacters = [];
      return;
    }
    const files = this.app.vault.getFiles().filter(
      (f) => f.path.startsWith(`${bookRoot}/characters/`) && f.extension === "md" && !f.name.startsWith("_")
    );
    this.cachedCharacters = files.map((f) => ({ name: f.basename }));
  }
  getSidebarView() {
    const leaves = this.app.workspace.getLeavesOfType(NarrativeSidebarView.VIEW_TYPE);
    if (!leaves.length)
      return null;
    const view = leaves[0].view;
    return view instanceof NarrativeSidebarView ? view : null;
  }
  // ---------------------------------------------------------------------------
  // Create new book
  // ---------------------------------------------------------------------------
  async createNewBook() {
    new CreateBookModal(this.app, async (title, folderName) => {
      try {
        const vault = this.app.vault;
        const base = folderName;
        const subfolders = ["chapters", "characters", "locations", "world", "notes"];
        for (const sub of subfolders) {
          const path = (0, import_obsidian9.normalizePath)(`${base}/${sub}`);
          if (!vault.getAbstractFileByPath(path)) {
            await vault.createFolder(path);
          }
        }
        const config = {
          title,
          author: "",
          backendUrl: "http://localhost:8000",
          folders: {
            chapters: "chapters",
            characters: "characters",
            locations: "locations",
            world: "world",
            notes: "notes"
          }
        };
        const markerPath = (0, import_obsidian9.normalizePath)(`${base}/.narrative-book.json`);
        if (!vault.getAbstractFileByPath(markerPath)) {
          await vault.create(markerPath, JSON.stringify(config, null, 2));
        }
        const sampleChapter = (0, import_obsidian9.normalizePath)(`${base}/chapters/01-chapter.md`);
        if (!vault.getAbstractFileByPath(sampleChapter)) {
          await vault.create(sampleChapter, `---
chapter: 1
title: "Chapter One"
location: "[[Location Name]]"
timeline: "Year 1, Day 1"
characters:
  - "[[Character One]]"
  - "[[Character Two]]"
pov: "[[Character One]]"
status: draft
word_target: 3000
---

Narrative text of the first scene. Describe setting, action, inner thoughts.

[character: Character One] \u2014 Dialogue goes here.
[character: Character Two] \u2014 Response goes here.

More narrative between the dialogue lines.

---
location:: [[Another Location]]
timeline:: Year 1, Day 1, later

Second scene starts after the scene break. New location and time can be set
with Dataview inline syntax above (location:: and timeline::).

[character: Character One] \u2014 A line in the second scene.
`);
        }
        const charTemplate = (0, import_obsidian9.normalizePath)(`${base}/characters/_template.md`);
        if (!vault.getAbstractFileByPath(charTemplate)) {
          await vault.create(charTemplate, `---
type: character
full_name: ""
aliases: []
appears_in: []
role: supporting
status: alive
age:
faction: ""
---

## Description

Physical appearance, voice, mannerisms.

## Background

History before the story starts.

## Arc

How they change over the course of the book.

## Notes

- Private observations, things the reader doesn't know yet
`);
        }
        const locTemplate = (0, import_obsidian9.normalizePath)(`${base}/locations/_template.md`);
        if (!vault.getAbstractFileByPath(locTemplate)) {
          await vault.create(locTemplate, `---
type: location
location_type: city
parent: ""
appears_in: []
climate: ""
population: ""
controlled_by: ""
---

## Description

Atmosphere, sights, sounds, smells.

## Key places

- **Place name** \u2014 what happens here

## History

How it came to be this way.
`);
        }
        const worldTemplate = (0, import_obsidian9.normalizePath)(`${base}/world/_template.md`);
        if (!vault.getAbstractFileByPath(worldTemplate)) {
          await vault.create(worldTemplate, `---
type: world_element
element_type: magic_system
related_locations: []
---

## Rules

1. First rule
2. Second rule

## Limitations

- What it cannot do
- Cost or drawback
`);
        }
        const readme = (0, import_obsidian9.normalizePath)(`${base}/README.md`);
        if (!vault.getAbstractFileByPath(readme)) {
          await vault.create(readme, `# ${title}

## Structure

| Folder | Contents |
|--------|----------|
| \`chapters/\` | Story chapters \u2014 one file per chapter |
| \`characters/\` | Character profiles \u2014 one file per character |
| \`locations/\` | Location notes \u2014 one file per location |
| \`world/\` | World-building: magic, factions, history, etc. |

## Chapter format

\`\`\`markdown
---
chapter: 1
title: "Chapter Title"
location: "[[Location Name]]"    \u2190 wikilink \u2192 auto-creates location note
timeline: "Year 1, Day 1"
characters:
  - "[[Character Name]]"         \u2190 wikilink \u2192 auto-creates character note
pov: "[[Character Name]]"
status: draft                    \u2190 draft / revision / final
word_target: 3000
---

Narrative text here.

[character: Name] \u2014 Dialogue line.  \u2190 plugin hides the marker, shows only text

---
location:: [[New Location]]         \u2190 scene break with new location
timeline:: Year 1, later

Second scene narrative.
\`\`\`

## Character format

See \`characters/_template.md\`

## Dataview queries

Install the Dataview plugin to use these:

**All characters:**
\`\`\`dataview
TABLE role, status FROM "${base}/characters"
WHERE type = "character"
SORT file.name ASC
\`\`\`

**Chapter timeline:**
\`\`\`dataview
TABLE timeline, location, status FROM "${base}/chapters"
SORT chapter ASC
\`\`\`

## Backend

This book uses: \`http://localhost:8000\`
Change in \`.narrative-book.json\` if running on a different port.
`);
        }
        const timelinePath = (0, import_obsidian9.normalizePath)(`${base}/timeline.md`);
        if (!vault.getAbstractFileByPath(timelinePath)) {
          await vault.create(timelinePath, `# Timeline

| title | year | month | day | hour | minute | location | characters | chapter |
|-------|------|-------|-----|------|--------|----------|------------|---------|
`);
        }
        new import_obsidian9.Notice(`Book "${title}" created in ${folderName}/`);
        const chapterFile = vault.getAbstractFileByPath(sampleChapter);
        if (chapterFile instanceof import_obsidian9.TFile) {
          const leaf = this.app.workspace.getLeaf();
          await leaf.openFile(chapterFile);
        }
      } catch (err) {
        new import_obsidian9.Notice(`Failed to create book: ${err}`);
        console.error("[Narrative Forge] Create book error:", err);
      }
    }).open();
  }
  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------
  getBackendUrl() {
    if (this.settings.backendMode === "external") {
      return (this.settings.externalUrl || "http://localhost:8000").replace(/\/$/, "");
    }
    return "http://localhost:8000";
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  registerAutoImport() {
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (!(file instanceof import_obsidian9.TFile))
          return;
        if (!file.path.endsWith(".md") && !file.path.endsWith(".nos"))
          return;
        if (file.path.includes("/characters/") || file.path.includes("/locations/") || file.path.includes("/world/"))
          return;
        const existing = this.autoImportDebounceMap.get(file.path);
        if (existing)
          clearTimeout(existing);
        const timer = setTimeout(async () => {
          this.autoImportDebounceMap.delete(file.path);
          try {
            if (file.path.endsWith(".md")) {
              const bookResult = await this.bookManager.findBook(file.path);
              if (bookResult) {
                const { config, bookRoot } = bookResult;
                const chapterFolder = bookRoot ? `${bookRoot}/${config.folders.chapters}` : config.folders.chapters;
                if (file.path.startsWith(chapterFolder)) {
                  await this.bookManager.syncChapterMetadata(file, bookRoot, config);
                }
              }
              await this.api.importBook(false, this.getAbsoluteBookDir(), this.currentBookLanguage).catch(() => {
              });
            } else if (file.path.endsWith(".nos")) {
              await this.api.importBook(false, this.getAbsoluteBookDir(), this.currentBookLanguage).catch(() => {
              });
            }
          } catch (e) {
          }
        }, 2e3);
        this.autoImportDebounceMap.set(file.path, timer);
      })
    );
  }
  /**
   * On startup: find all books in the vault and trigger incremental import
   * for each one (hash-based, so unchanged files are skipped quickly).
   */
  async startupReindex() {
    var _a, _b;
    const adapter = this.app.vault.adapter;
    if (!(adapter instanceof import_obsidian9.FileSystemAdapter))
      return;
    const vaultBase = adapter.getBasePath();
    const bookRoots = [];
    if (await adapter.exists(".narrative-book.json")) {
      bookRoots.push("");
    }
    try {
      const listing = await adapter.list("/");
      for (const folder of listing.folders) {
        const markerPath = (0, import_obsidian9.normalizePath)(`${folder}/.narrative-book.json`);
        if (await adapter.exists(markerPath)) {
          bookRoots.push(folder);
        }
      }
    } catch (e) {
    }
    for (const bookRoot of bookRoots) {
      const markerPath = bookRoot ? `${bookRoot}/.narrative-book.json` : ".narrative-book.json";
      const absBookDir = bookRoot ? `${vaultBase}/${bookRoot}` : vaultBase;
      let backendUrl = "http://localhost:8000";
      try {
        const raw = await adapter.read(markerPath);
        const config = JSON.parse(raw);
        backendUrl = (_a = config.backendUrl) != null ? _a : backendUrl;
      } catch (e) {
      }
      if (this.currentBookRoot == null) {
        this.currentBookRoot = bookRoot;
        try {
          const markerRaw = await adapter.read(markerPath).catch(() => "{}");
          this.currentBookLanguage = (_b = JSON.parse(markerRaw)["language"]) != null ? _b : "uk";
        } catch (e) {
          this.currentBookLanguage = "uk";
        }
        this.api.setBaseUrl(backendUrl);
        console.log(`[Narrative Forge] Active book: ${absBookDir}`);
      }
      try {
        const api = new NarrativeAPI(backendUrl);
        await api.importBook(false, absBookDir, this.currentBookLanguage);
        console.log(`[Narrative Forge] Startup reindex done: ${bookRoot || "vault root"}`);
      } catch (e) {
      }
    }
  }
  async runImport(force = false) {
    const notice = new import_obsidian9.Notice("Narrative Forge: Importing...", 0);
    try {
      const result = await this.api.importBook(force, this.getAbsoluteBookDir(), this.currentBookLanguage);
      notice.hide();
      new import_obsidian9.Notice(
        `Narrative Forge: Imported ${result.chapters_imported} chapter(s), ${result.characters_found} character(s).` + (result.errors.length > 0 ? ` ${result.errors.length} error(s).` : "")
      );
      void this.reloadCharacterCache();
    } catch (err) {
      notice.hide();
      new import_obsidian9.Notice(`Narrative Forge: Import failed \u2014 ${err}`);
    }
  }
  async testConnection() {
    const details = await this.api.healthDetails();
    if (details) {
      new import_obsidian9.Notice(
        `Narrative Forge: Connected. ${details.chapters} chapters, ${details.characters} characters. Provider: ${details.provider}`
      );
    } else {
      new import_obsidian9.Notice("Narrative Forge: Cannot reach backend. Is it running?");
    }
  }
  async activateSidebar() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(NarrativeSidebarView.VIEW_TYPE)[0];
    if (!leaf) {
      const leftLeaf = workspace.getLeftLeaf(false);
      if (!leftLeaf)
        return;
      leaf = leftLeaf;
      await leaf.setViewState({
        type: NarrativeSidebarView.VIEW_TYPE,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
  async activateChat() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(NarrativeChatView.VIEW_TYPE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf)
        return;
      leaf = rightLeaf;
      await leaf.setViewState({
        type: NarrativeChatView.VIEW_TYPE,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
  }
  async activateTimeline() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(NarrativeTimelineView.VIEW_TYPE)[0];
    if (!leaf) {
      leaf = workspace.getLeaf("tab");
      await leaf.setViewState({
        type: NarrativeTimelineView.VIEW_TYPE,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
    const view = leaf.view;
    if (view instanceof NarrativeTimelineView)
      void view.refresh();
  }
  /**
   * Open chat panel and return the NarrativeChatView instance.
   * Used by the "Send to chat" context menu item.
   */
  async activateChatAndGetView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(NarrativeChatView.VIEW_TYPE)[0];
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (!rightLeaf)
        return null;
      leaf = rightLeaf;
      await leaf.setViewState({
        type: NarrativeChatView.VIEW_TYPE,
        active: true
      });
    }
    workspace.revealLeaf(leaf);
    const view = leaf.view;
    if (view instanceof NarrativeChatView) {
      return view;
    }
    return null;
  }
};
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {});
